import js from "@eslint/js";
import globals from "globals";

export default [
    {
        ignores: [
            ".venv/**",
            "node_modules/**",
            "tests/**",
            "dist/**",
            "build/**",
            "sto_crm/assets/app.js"
        ]
    },
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "module",
            globals: {
                ...globals.browser,
                // Core state / constants
                state: "writable",
                routes: "readonly",
                routeSubtitles: "readonly",
                priorityLabels: "readonly",
                orderStatusTransitions: "readonly",
                channelLabel: "readonly",
                channelLabels: "readonly",
                appointmentStatusFallback: "readonly",
                itemApprovalFallback: "readonly",
                BOOTSTRAP_CACHE_KEY: "readonly",
                BOOTSTRAP_CACHE_SCHEMA_VERSION: "readonly",
                BOOTSTRAP_CACHE_TTL_MS: "readonly",
                MAX_ORDER_ITEMS: "readonly",
                EXPORT_ENTITIES: "readonly",
                ENTITY_COLLECTION_PATHS: "readonly",
                BUTTON_STYLE_CLASSES: "readonly",

                // Core DOM helpers
                $: "readonly",
                $$: "readonly",
                esc: "readonly",
                highlightText: "readonly",
                buttonClassName: "readonly",
                safeExternalUrl: "readonly",
                safeInlinePrintScript: "readonly",
                safeRecordId: "readonly",
                stableElementId: "readonly",
                assertSafeModalMarkup: "readonly",
                inEditable: "readonly",
                clampPercent: "readonly",
                widthClassFromPercent: "readonly",
                money: "readonly",
                moneyCompact: "readonly",
                qty: "readonly",
                num: "readonly",
                parseNumericInput: "readonly",
                pluralRu: "readonly",
                bytesText: "readonly",
                helpTip: "readonly",
                textOrDash: "readonly",
                dateOrDash: "readonly",
                statusBadge: "readonly",
                appointmentStatusBadge: "readonly",
                classToken: "readonly",
                toneToken: "readonly",
                semanticToneClass: "readonly",
                setHTMLSafe: "readonly",
                dateShort: "readonly",
                prefersReducedMotion: "readonly",

                // Core storage
                SafeLocalStorage: "readonly",
                safeStorageGet: "readonly",
                safeStorageSet: "readonly",
                cacheBootstrap: "readonly",
                readCachedBootstrap: "readonly",
                reconcileDataVersions: "readonly",
                clearCachedBootstrap: "readonly",

                // Core API
                api: "readonly",
                requiresFreshCsrf: "readonly",

                // Core Routing
                requestedRoute: "writable",
                currentRouteFromLocation: "readonly",
                setRoute: "readonly",
                loadData: "readonly",
                render: "readonly",
                routeFromLocation: "readonly",

                // app_main / UI rendering functions
                announce: "readonly",
                toast: "readonly",
                showToast: "readonly",
                showError: "readonly",
                setLoadingState: "readonly",
                setOnlineState: "readonly",
                updateSearchClear: "readonly",
                offlineBannerHtml: "readonly",
                errorBannerHtml: "readonly",
                contextStripHtml: "readonly",
                renderDashboard: "readonly",
                renderAppointments: "readonly",
                renderOrders: "readonly",
                renderCustomers: "readonly",
                renderVehicles: "readonly",
                renderCatalog: "readonly",
                renderInventory: "readonly",
                renderReports: "readonly",
                renderUpdates: "readonly",
                initKanbanDragAndDrop: "readonly",
                bindCatalogFilter: "readonly",
                bindWorkspaceToolbar: "readonly",
                updateScrollHints: "readonly",
                applyCellTitles: "readonly",
                updateNavigationBadges: "readonly",
                resetWorkspaceToolbarObserver: "readonly",
                noticeHtml: "readonly",
                initUpdates: "readonly",
                SkeletonBuilder: "readonly",
                catalogModels: "readonly",
                catalogMakeHtml: "readonly",
                emptyState: "readonly",
                vehicleOptions: "readonly",
                datalistOptions: "readonly",
                hasOrderFilter: "readonly",
                bindViewActions: "readonly",
                closeTransientPanels: "readonly",
                checkForUpdates: "readonly",
                renderShell: "readonly",
                setMobileNavOpen: "readonly",
                downloadCsv: "readonly",
                openCustomerModal: "readonly",
                openInventoryModal: "readonly",
                entityRecordPath: "readonly",
                entityCollectionPath: "readonly"
            }
        },
        rules: {
            "no-unused-vars": "off",
            "no-undef": "error",
            "no-duplicate-imports": "error",
            "no-self-compare": "error",
            "no-template-curly-in-string": "error"
        }
    }
];
