# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('sto_crm/assets/__init__.py', 'sto_crm/assets'),
        ('sto_crm/assets/index.html', 'sto_crm/assets'),
        ('sto_crm/assets/app.css', 'sto_crm/assets'),
        ('sto_crm/assets/app.js', 'sto_crm/assets'),
    ],
    hiddenimports=[
        'sto_crm',
        'sto_crm.assets',
        'sto_crm.catalog',
        'sto_crm.cli',
        'sto_crm.config',
        'sto_crm.database',
        'sto_crm.export',
        'sto_crm.http_server',
        'sto_crm.printing',
        'sto_crm.queries',
        'sto_crm.reports',
        'sto_crm.runtime',
        'sto_crm.seed',
        'sto_crm.services',
        'sto_crm.updates',
        'sto_crm.validation',
        'sto_crm.web',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='STO_CRM',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
