// Shared static UI contracts for packaged smoke checks.
// Keep this list focused on stable public behaviour and accessibility hooks;
// avoid adding strings that exist only to satisfy the tests.

const REQUIRED_SUBSTRINGS = [
  // a11y / dirty-state / общий shell
  "function labeledField(",
  "function tableHead(",
  "function inputField(",
  "function selectField(",
  "function textareaField(",
  'inputField("customer", "name"',
  'selectField("order", "customer_id"',
  "modalDirty",
  "pipelineBoard(r.pipeline_by_status || [])",
  "appointmentTimeline(r.appointment_load_7_days || [])",
  "procurementList(r.procurement_plan || [])",
  "workloadList(r.workload_by_responsible || [])",
  "actionPlanList(r.action_plan || [])",
  "action-center",
  "data-route-target=",
  "findAppointmentById(id)",
  "findCustomerById(id)",
  "findVehicleById(id)",
  "findInventoryById(id)",
  'function requireRecord(record, label = "Запись")',
  'if (requireRecord(customer, "Клиент")) openCustomerModal(customer);',
  'if (requireRecord(part, "Складская позиция")) openInventoryModal(part);',
  "if (!vehicle?.id) return vehicleOptions(selectedCustomer, order.vehicle_id);",
  "if (vehicle.deleted_at || vehicle.deleted_at === 1 || vehicle.vehicle_deleted) {",
  "healthMetric(r)",
  'confirm("Закрыть окно без сохранения изменений?")',
  "shouldKeepModalForEscape",
  "function handleCommandPaletteTab(event)",
  "lastFocusedElement.focus({ preventScroll: true });",
  'modalSize = allowedSizes.has(size) ? size : ""',
  "setSaveButtonsBusy",
  "Вне склада / заказная",
  "Источник запчасти",
  "discountPreview",
  'aria-label="Удалить позицию заказ-наряда"',
  "function contextStripHtml()",
  "function updateNavigationBadges()",
  'data-nav-badge="dashboard"',
  'data-nav-badge="updates"',
  "lastLoadedAt",
  "try {",
  "viewHtml = renderers[state.route]();",
  "content.innerHTML = `${offlineBannerHtml()}${errorBannerHtml()}${contextStripHtml()}${viewHtml}`;",
  'if (!force && !state.offlineMode) return "";',
  "offlineBannerHtml(true)",
  "Не удалось отрисовать раздел.",
  "function announce(message",
  "function errorBannerHtml()",
  'data-action="dismiss-error"',
  "scroll-hint-sr",
  "aria-describedby",
  'aria-label="Запись"',
  'aria-label="Открыть клиента ${esc(c.name || c.id)}"',
  "function classToken(",
  'aria-label="Тип позиции"',
  'aria-label="Фильтр по марке или модели"',
  'role="group" aria-label="Фильтр заказов по статусу"',
  'role="option" data-command-index',
  'role="menuitem"',
  'aria-haspopup="menu"',
  'aria-pressed="${state.status === status ? "true" : "false"}"',
  "const nextStatus = source.dataset.status;",
  "state.data.app.csrf_token",
  'function requiresFreshCsrf(actionName = "это действие")',
  "Сессия безопасности устарела. Обновите данные CRM и повторите действие.",
  'if (state.route === "orders" && state.status !== "all")',
  "const needsRouteFilterReload = hasOrderFilter && (",
  'data-reload-before-action="1"',
  "function exportUrl(entity)",
  "async function downloadCsv(entity)",
  'data-action="export-csv"',
  '<button class="btn ghost" type="button" data-action="export-csv"',
  "openPrintOrder(id)",
  'window.open("about:blank", "_blank")',
  "printWindow.opener = null;",
  'data-action="duplicate-order"',
  'aria-label="Печать заказ-наряда',
  "Прокрутите вправо",

  // Forms
  "function applyFormError(error)",
  "function clearFormError(target)",
  "applyFormError(error);",
  'target.setAttribute("aria-invalid", "true")',
  "field-error",
  "clearAllFormErrors(form)",
  'min="0.01" required value="${esc(item.quantity || 1)}"',
  'const invalidItems = state.orderDraftItems.filter(item => !String(item.title || "").trim() || num(item.quantity, 0) <= 0);',

  // Shortcuts / vehicle+customer selection
  'const routeKeys = { d: "dashboard", p: "dashboard"',
  'k: "catalog"',
  'keys: "G D", run: () => setRoute("dashboard")',
  'keys: "G K", run: () => setRoute("catalog")',
  'data-tooltip="Каталог марок и моделей · G K"',
  'const placeholderText = customers.length ? "Выберите клиента" : "Нет клиентов";',
  'data-tooltip="Создать заказ-наряд · N O"',
  "Новый заказ <kbd>N O</kbd>",
  'const placeholder = normalizedCustomerId || normalizedSelected ? "Не выбран" : "Сначала выберите клиента";',
  "} else if (vehicleId !== normalizedSelected) {",
  'const selectedCustomer = appointment.customer_id || "";',
  'const selectedCustomer = vehicle.customer_id || "";',
  'const selectedCustomer = order.customer_id || "";',
  'return normalize(value) || normalize(fallback) || "#";',

  // Updates
  'data-route="updates"',
  "function renderUpdates()",
  "/api/update/status",
  "/api/update/install",
  'data-action="check-update"',
  'data-action="install-update"',
  "STO_CRM.exe",
  "latest.json",
  "GitHub Releases",

  // Theme / palette / history
  'themeToggle.addEventListener("click"',
  "function applyDensity(",
  "if (!node) {",
  "function toggleDensity()",
  "function commandItems()",
  "function openCommandPalette()",
  "data-command-index",
  "Ctrl+K",
  "history.pushState",
  'window.addEventListener("popstate"',
  "appTabbableSnapshot",
  "bindModalSubmitHandlers",
  "safeStorageGet",
  "nextThemePreference",
  "localStorage.removeItem(key)",
  "handleModalKeydown",
  'if ("inert" in app) {\n            app.removeAttribute("aria-hidden");',
  'if (isMobile && !nextOpen && !hasNativeInert) sidebar.setAttribute("aria-hidden", "true");',
  'id="modalBackdrop" role="presentation" hidden',
  'id="commandPalette" role="presentation" hidden',

  // Premium headings
  "function sectionIntro(title, text, options = {})",
  '"section-card hero-card"',
  "hero-stat-stack",
  "metric-icon",
  "insight-icon",
  "Premium workspace",
  "Смена под контролем",
  "primary-kpi-grid",
  "function pluralRu(",
  "function moneyCompact(",
  "function viewHeading(",
  "view-heading-actions",
  "Календарь приемки",
  "Заказ-наряды",
  "Каталог автомобилей",
  "Отчеты и аналитика",
  'action: "open-action-plan"',
  "workspace-grid",
  "function riskRadar(report)",
  "function quickActions()",
  "function miniLedger(report)",
  'sectionIntro("Смена под контролем"',
  'class="primary-kpi-grid"',

  // Retry / network
  "bindViewActions(content);",
  "error.retryable = response.status >= 500 || [408, 425, 429].includes(response.status);",
  "const retryable = error?.retryable === true || !Number(error?.status || 0);",
  "if (attempt === maxRetries || !retryable) throw error;",
  'if (method !== "GET" && !state.data?.app?.csrf_token)',
  "function readCachedBootstrap() {",
  "sessionStorage can be unavailable or contain stale data",
  "if (state.updateLoading) return;",
  "state.updateCheckScheduled = true;",
  'const content = $("#content");\n    if (!content) return;',
  "window.setTimeout(() => URL.revokeObjectURL(url), 1000);",

  // DOM hooks used from index.html that must live inside JS
  '$("#modalBackdrop").classList.add("open");',
  '$("#commandPalette")?.classList.add("open");',
  ".modal-backdrop[hidden], .command-palette-backdrop[hidden]",
];

const FORBIDDEN_SUBSTRINGS = [
  '<div class="field"><label>',
  'data-route="inspections"',
  "new-inspection",
  "openInspectionModal",
  "lookupCustomers[0]?.id",
  '<a class="btn ghost" href="#" data-action="export-csv"',
  'id="modalBackdrop" role="presentation" aria-hidden="true" hidden',
  'id="commandPalette" role="presentation" aria-hidden="true" hidden',
  'backdrop.setAttribute("aria-hidden", "true");',
  'palette.setAttribute("aria-hidden", "true");',
  "?token=${token}",
  'window.open("about:blank", "_blank", "noreferrer")',
  'URL.revokeObjectURL(url);\n    toast("CSV экспортирован")',
  "Digital Vehicle Inspection",
];

module.exports = { REQUIRED_SUBSTRINGS, FORBIDDEN_SUBSTRINGS };
